//var scoreJohn,scoreMike,scoreMary;
//var scoreJohn = (89+120+103)/3;
//var scoreMike = (116+94+123)/3;
//var scoreMike = (97+137+105)/3;

//if(teamJohn > teamMike && scoreJohn > scoreMary){
//    console.log('teamJohn is having higher average');
//}
//else if(teamJohn==teamMike){
  //  console.log('match draw');
//}
//else {
//    console.log('teamMike is having highest average');
//}












//defining a function
function funName(){
    console.log("hello world");
}

//calling a function
funName();
//function defination
function calculateAge(birthYear){
    console.log(2018 - birthYear);
//return will take out the value outside which is generated within finctn
    return 2018 - birthYear;
}
//storing the value which is generated by the function
var ageJohn = calculateAge(1990);
console.log(ageJohn);


//reusing function
function calculateAge(birthYear){
//return will take out the value outside which is generated within finctn
    return 2018 - birthYear;
}
var ageJohn =calculateAge(1990);
var ageMary =calculateAge(1948);
var ageMike =calculateAge(1969);
console.log(ageJohn,ageMary,ageMike);




//declaring a function
function yearsUntilRetirement(year,firstName){
    var age = calculateAge(year);
    var retirement = 65 - age;

if (retirement > 0){
    console.log(firstName + 'retires in' + retirement + ' years. ');

}
else{
    console.log(firstName +'is already retired.');
}
}
yearsUntilRetirement(1990,ageJohn);
yearsUntilRetirement(1948,ageMary);



//FUNCTN EXpression
var whatDoYouDo = function(job,firstName){
    switch(job){
        case 'teacher':
            return 'teaches kids hw to code';
        case 'driver':
            return 'designs websites';
        default:
            return 'does smthg else';      
    }
}
console.log(whatDoYouDo('teacher', 'John'));
console.log(whatDoYouDo('designer','Mark'));
console.log(whatDoYouDo('retired','Jane'));


//initializing an array
var names = ['John','Mark','Jane'];
var years = new Array(1990,1969,1948);
console.log(names[2]);
console.log(names.length);

//mutate array data
names[1] = 'Ben';
names[names.length]= 'Mary';
console.log(names);


//Different data types
var john = ['John','Smith',1990,'designer',false,1990];
//add element at the end of an array
john.push('blue');
//adds an element from the starting index from an array
john.unshift('mr.');
console.log(john);

john.pop();
john.pop();
//removes an element from end of an array
john.shift();
console.log(john);
console.log(john.indexOf(23));
console.log(john.indexOf(1990));


var isDesigner = john.indexOf('designer') === -1 ? 'John is NOT a designer' :'John is a designer';
console.log(isDesigner);